model_list:
  - model_name: qwen2.5:32b
    litellm_params:
      model: openai/Qwen2.5-32B-Instruct-AWQ
      api_base: "http://127.0.0.1:8002/v1"
      api_key: "sk-local-vllm"
  - model_name: llama3.1:8b
    litellm_params:
      model: openai/llama3.1:8b
      api_base: "http://127.0.0.1:11434/v1"
      api_key: "sk-local-ollama"

litellm_settings:
  drop_params: true
  success_callback: ["prometheus"]
